name: Test scraper

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * 1-5"
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - run: go test -timeout 30s -v ./...
